version: '3.8'
services:
  database:
    image: mongo:latest
    volumes:
      - lemoncode-data:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks: 
        - lemoncode-challenge
  backend:
    depends_on:
      - database
    build: ./backend/backend
    ports:
      - "5000:80"
    restart: always
    environment:
      MONGO_URI: database:27017
    networks: 
      - lemoncode-challenge
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "3000:80"
    restart: always
    environment:
      REACT_APP_API_URL: https://localhost:5000/api/topics
    networks: 
      - lemoncode-challenge
volumes:
    lemoncode_data:
networks:
    lemoncode-challenge: